name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}
          registry: docker.pkg.github.com
          repository: matchory/docker-ssh-tunnel/docker-ssh-tunnel
          tag_with_ref: true
          tags: latest
